name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx"
      
    - name: Create Tests Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: "Pluto.Rover.Tests/TestResults/test-results.trx"                            
        reporter: dotnet-trx

    - name: Create Simulations Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Simulation Results
        path: "Pluto.Rover.Simulations/TestResults/test-results.trx"                            
        reporter: dotnet-trx
